ADDIE_SOFT_PLATFORM_NAME: "ADDIE SOFT  E-LEARNING PLATFORM"
ADDIE_SOFT_WELCOME_MESSAGE: "Your Online Classroom"

ADDIE_SOFT_PRIMARY_COLOR: "#3b85ff" # cool blue

# Footer links are dictionaries with a "title" and "url"
# To remove all links, write:
# ADDIE_SOFT_FOOTER_NAV_LINKS: []
# ADDIE_SOFT_FOOTER_LEGAL_LINKS: []
ADDIE_SOFT_FOOTER_NAV_LINKS:
    - title: "About"
      url: "/about"
    - title: "Contact"
      url: "/contact"
ADDIE_SOFT_FOOTER_LEGAL_LINKS:
    - title: "Copyright © 2021 ADDIE SOFT LTD."
      url: "https://www.addiesoft.com"